### ISSUE TITLE
Expand WebCrawler README to include docker-compose instructions

### ISSUE THREAD

**Issue by Aaronontheweb** [petabridge/akkadotnet-code-samples#70]
https://github.com/petabridge/akkadotnet-code-samples/blob/master/Cluster.WebCrawler/README.md

**Comment by aventurella** [comment]
The docker-compose file specifies:

```
environment:
      CLUSTER_SEEDS: "akka.tcp://webcrawler@lighthouse:4053"
      CLUSTER_IP: webcrawler.crawlservice
      CLUSTER_PORT: 0
```

Searching though the codebase, where are these read and applied to the `hocon.config`?
